### ISSUE TITLE
Partizants- HP marker

### ISSUE THREAD

**Issue by Liir6676** [baktrius/nhexonline#10]
Losowa kolejność pułapek jest pożądana. Prośba, żeby dopracować pozycję HP, aby zawsze było pierwsze.

**Comment by baktrius** [comment]
Funkcjonalność mieszania znaczników zdaje mi się być dość niszowa.
Dodałem ją jako tymczasowe rozwiązanie i zamiast ją rozwijać wolałbym dodać coś bardziej uniwersalnego.
Myślałem o pojemnikach na żetony, ale jeszcze mi się ten pomysł niewyklarował.
Podsumowując, jestem mało zainteresowany dopieszczeniem mechaniki pod jedną armię
natomiast jestem otwarty na sugestie nowych mechanik (w nowych issues), które rozwiązywałyby problem w sposób ogólny/generyczny.
