### ISSUE TITLE
Allow Multiplicity 0

### ISSUE THREAD

**Issue by Liir6676** [baktrius/nhexonline#20]
![image](https://github.com/user-attachments/assets/6c3680e3-63ef-4818-9c9d-037a226fb7df)
Przyjemniejsze dla ludzi balansujących swoje armie (wartość 0 zamiast usuwania jednostki, a potem ponownego jej dodawania).
Przede wszystkim rozwiązuje to problem cursed nadmiarowego znacznika Partyzantów.

**Comment by baktrius** [comment]
Done in c4d89ef

**Comment by Liir6676** [comment]
Działa dobrze!
