### ISSUE TITLE
Army order

### ISSUE THREAD

**Issue by Liir6676** [baktrius/nhexonline#26]
![image](https://github.com/user-attachments/assets/dff0208d-c8d5-4383-b877-dc25124dd01c)
Na załączonym obrazie widać, że armie prywatne i customowe są przed zwykłymi. Gorąco proponuję, by custom armie getowało się z oddzielnej rubryki "Get custom army" (a w niej, czy takowa będzie publiczna czy prywatna to już nie problem).
Ponad to armie oficjalne są w kolejności, w której były dodawane do bazy. Proponuję:
![image](https://github.com/user-attachments/assets/210893e3-3678-45b9-aeb4-dcc159700a87)
Żeby można było z tego poziomu określać priorytet armii, wówczas każdy administrator serwisu będzie miał dowolność, czy ustawi je sobie alfabetycznie, czy w kolejności wychodzenia na rynek itp.
Będą to wygodne zmiany, ponieważ będzie się dzięki nim można przyzwyczajać do położenia danych armii. Obecnie jest to niemożliwe, zbyt wiele powyższych czynników wpływa na kolejność.

**Comment by baktrius** [comment]
Reorganizacja armii na dwie pozycje w menu brzmi ok. Jeśli chodzi o ich pozycję w menu to myślę, że powinny być ułożone alfabetycznie (nie widzę za bardzo sytuacji, w której administrator chciałby, żeby było inaczej + nie wiem jak miałby to wygodnie konfigurować).

**Comment by Liir6676** [comment]
Można też jak najbardziej narzucić standard alfabetyczny. To już jak najbardziej wystarczające. Przykładowo, jeśli community uznałoby, że byłoby wygodniej, gdyby armie były posortowane inaczej np. podstawka, a następnie kolejno każdy dodatek, który wychodził- fajnie byłoby mieć opcję w CHANGE ARMY - Priority (zgodnie z którym armia zajmowałaby odpowiednią kolejność w menu kontekstowym- wówczas funkcję priority proponuję dodać również dla instrukcji, które aktualnie zawarte są na osobnej liście. Chyba, że pomysł intrukcji wywoływanej z poziomu Token Spawnera ma szansę bytu w przyszłości- to wtedy nie ma co się dwa razy nachylać nad instrukcjami).

**Comment by Liir6676** [comment]
> Reorganizacja armii na dwie pozycje w menu brzmi ok. Jeśli chodzi o ich pozycję w menu to myślę, że powinny być ułożone alfabetycznie (nie widzę za bardzo sytuacji, w której administrator chciałby, żeby było inaczej + nie wiem jak miałby to wygodnie konfigurować).

Reorganizacja załatwi też mam nadzieję problem armii fanowskich znajdujących się w puli do wylosowania przez Get Army > Random. Czy zrobić do tego osobny issue? Czy jest sens prosić o dwa różne Get Army Custom i Get Army (default-official)?

**Comment by Liir6676** [comment]
Wpadłem na jeszcze jeden, może prostszy sposób. Może dałoby się zostawić kolejność do ogarniania całkowicie po stronie admina? Np. kolejność w panelu admina mogłaby się pokrywać z kolejnością wyświetlaną na stronie- problem w tym, że aktualnie w panelu admina, jedyny sposób na zamianę kolejności, to usuwanie i dodawanie wpisów w odpowiedniej kolejności, co jest nieefektywne i czasochłonne.

Rozwiązałoby to problem:
- kolejności armii
- kolejności linków do instrukcji
- kolejności wszelkich innych elementów

Nadal pozostanie problem:
- oddzielenia armii custom od official

**Comment by Liir6676** [comment]
> Reorganizacja armii na dwie pozycje w menu brzmi ok. Jeśli chodzi o ich pozycję w menu to myślę, że powinny być ułożone alfabetycznie (nie widzę za bardzo sytuacji, w której administrator chciałby, żeby było inaczej + nie wiem jak miałby to wygodnie konfigurować).

W liście linków chociażby FAQ czy General fajnie by było mieć możliwość ustawienia na górze.

**Comment by baktrius** [comment]
Widzę, że rzecz jest do ogarnięcia tzn. są pluginy do django, żeby można było sortować elementy bezpośrednio w admin panelu. Popróbuję i zobaczę co da się zrobić.

**Comment by baktrius** [comment]
Część dotycząca ustawiania kolejności linków i armii (w obrębie jednej grupy public / custom / official) zrobiona w a502035 i 3ec5956.
Jako, że skorzystałem z dodatkowego pluginu do django to aby zaktualizować projekt do tej wersji należy zainstalować brakujący pakiet (`npm run install`).

**Comment by baktrius** [comment]
Rozdzielenie armii na kilka pozycji w menu zrobione w 593b195.
Tym samym uważam, że główne wątki tego issue zostały wypełnione.
Poboczne sprawy, jeśli zostały proponuję na bieżąco rozwiązywać w osobnych issues.
