### ISSUE TITLE
Separation of Armies

### ISSUE THREAD

**Issue by Liir6676** [baktrius/nhexonline#34]
![image](https://github.com/user-attachments/assets/52b05c70-b51d-4db7-8f2a-27068e2106d8)
W panelu administratora przydałoby się, aby armie administracji oraz armie pozostałe zostały rozdzielone np. na Admin Armies (armie których ownerem są gracze z uprawnieniami administratora, by łatwiej było odszukać się, gdy będzie dużo róznych armii i ułatwić dostęp do armii adminów, a więc przede wszystkim oficjalnych, common), Custom Armies (publiczne armie fanowskie nieadminów) i Private Armies (prywatne armie nieadminów). Pomogło by to bardzo w zarządzaniu armiami, szczegónie, gdy będzie ich już więcej.

**Comment by Liir6676** [comment]
Albo lepiej i łatwiej:
![image](https://github.com/user-attachments/assets/d4eafff3-84c8-4636-b6c2-5bbf4496009e)
Armies, Links i Tables mogłoby mieć takie "search" jak w Users oraz:
- Armies filtry od flag oraz filter "armie owned by staff status account"(czy coś w tym stylu)
- Links w przyszłości podział filtry na oficjalne i customowe
- Tables w przyszłości filtry na publiczne i prywatne

**Comment by baktrius** [comment]
Zobaczę co da się zrobić ale sugestie brzmią sensownie.

**Comment by baktrius** [comment]
Part regarding armies done in 08ba939.

Jeśli chodzi o linki to nie planowałem prywatnych i publicznych (temat na inne miejsce).
Jeśli chodzi o sekcje Tables to można to otworzyć w nowym issue kiedy będzie aktualne.
Takie wielowątkowe wiszące issue są dla mnie niewygodne.
Dlatego uznaję, że główna część tego issue jest zrobiona i je zamykam.

BTW: search działa zarówno po nazwach armii jak i po nickach ich autorów.
