### ISSUE TITLE
Edit- Remember front and back img

### ISSUE THREAD

**Issue by Liir6676** [baktrius/nhexonline#35]
![image](https://github.com/user-attachments/assets/8b96d5b0-120c-4464-abef-063de7a7c8d4)
Edycja byłaby o wiele szybsza i przyjemniejsza, gdyby:
![image](https://github.com/user-attachments/assets/ccf60161-6b74-4031-b82d-3d39250d857e)
Po naciśnięciu guzika edit back i front image były domyślnie od razu zaznaczone, konkretnie te, które były dotąd używane, aby nie trzeba było przy każdej edycji zawsze dodatkowo ustawiać front i back image.

**Comment by baktrius** [comment]
Tak zdecydowanie tak powinno być. To już kiedyś działało, a później się zepsuło. Spróbuję to naprawić.

**Comment by baktrius** [comment]
Done in a63628d.
