### ISSUE TITLE
Resources - Fire Wall

### ISSUE THREAD

**Issue by Liir6676** [baktrius/nhexonline#45]
Na kiedyś. Pytanie, czy formularz uploadu jest gotowy na ochronę przed plikami wykonywalnymi pod przykrywką formatu np. .jpg?
Może to już ogarnięte.
Jeśli nie i nie ma pomysłu na implementację, to pierwsze co mi przychodzi do głowy to uploadowanie "screenshota" pliku .jpg wgrywanego do serwisu. Na serwer trafiałaby wówczas tylko "screenshot" kopia (mam nadzieję bez utraty jakości).
Dzięki temu:
- złośliwe pliki nie zrobią nic poza zuploadowaniem się pod postacią graficznego szumu.
- być może można by to wykorzystać do tego by klienci mogli wgrywać więcej rodzajów plików. Ponieważ jeśli z każdego pliku robiłby się "screenshot", który po stronie serwera zawsze skończyłby w formacie dobrym dla przeglądarki (.jpg a może nawet bardziej wydajnym), to być może możnaby dopuścić również wrzucanie .png itp. (skoro ostatecznie i tak skończą jako .jpg)
- widzę jeden minus powyższego pomysłu, nie wiem jak miałyby wówczas wyglądać limity wielkości plików? Limity musiałyby zostać podane oddzielnie dla każdego formatu?

**Comment by baktrius** [comment]
Myślę, że serwis jest dość bezpieczny ze względu na tego typu atak. Ciężko mi to zapewnić, ponieważ nie jestem specjalistą bezpieczeństwa, natomiast nawet jeśli ktoś wgra niepożądany plik to przeglądarka u innych klientów próbuje wyświetlić go jedynie jako obrazek. Serwer również nigdy nie uruchamia uploadowanych plików. Ostatecznie myślę, że oszukanie serwera w ten sposób jest przynajmniej nieoczywiste i trudne.
Proponowane zabezpieczenie nie ma sensu bo jest po stronie klienta. Jeśli ktoś na porządnie zabierze się to hakowania strony to może je łatwo ominąć (atakujący po stronie klienta może robić co chce).
