### ISSUE TITLE
Manage Tokens - No files

### ISSUE THREAD

**Issue by Liir6676** [baktrius/nhexonline#47]
Jeśli spróbujemy wejść w podstronę Mange Tokens nie mając ani jednego pliku wgranego do armii, wówczas strona się wysypuje. Przychodzi mi do głowy kilka rozwiązań:
- najładniejsze: Button Manage Tokens jest bardziej wyblakły (Lub/i po najechaniu na niego kursorem będzie efekt {cursor: not-allowed;}) i nie klikalny do póki nie wykryty zostanie koknent w armii. Po najechaniu na niego wyskakuje dymek "first add resources".
- można też podobnie jak w powyższym przypadku po kliknięciu po prostu odsyłać siłą od razu do "Manage resources", byłoby to może prostsze w implementacji, ale nieintuicyjne.
- zapewne istnieją jeszcze jakieś rozwiązania.

**Comment by baktrius** [comment]
Fixed in f8b9992.
