### ISSUE TITLE
Token spawner- visual button

### ISSUE THREAD

**Issue by Liir6676** [baktrius/nhexonline#6]
![image](https://github.com/user-attachments/assets/0cfc4c77-aecb-438b-abef-057805958655)
Białe tło guzika "Next token" jest niewidoczne.

**Comment by baktrius** [comment]
Done in a18087f.

**Comment by Liir6676** [comment]
![image](https://github.com/user-attachments/assets/3434c1ae-45bf-4bc8-9768-3c8d837d9356)
Działa ładnie!

**Comment by Liir6676** [comment]
Nawet ładniej niż w starej wersji serwisu B)
