### ISSUE TITLE
Token spawner- highlighted

### ISSUE THREAD

**Issue by Liir6676** [baktrius/nhexonline#7]
![image](https://github.com/user-attachments/assets/c9bad463-55eb-46f5-87ca-10742679bd62)
Spawner po zaznaczeniu wyglądem trochę się rozjeżdża z podświetleniem zaznaczena.

**Comment by baktrius** [comment]
Done in 4516dd5.

**Comment by baktrius** [comment]
Done in 4516dd5.

**Comment by Liir6676** [comment]
Działa dobrze!
![image](https://github.com/user-attachments/assets/dd9356b1-9dec-4cb2-a6c5-a158ed2522b7)
